### ISSUE TITLE
running the script i get the following error

### ISSUE THREAD

**Issue by erasma** [PuKoren/rust-skins-config#1]
Sorry I don't understand this well enough - does it relate to the stats-table?

const workshopid = root.querySelector(".stats-table a")?.innerHTML;
                                                                ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47

**Comment by PuKoren** [comment]
What is the version of nodejs you are using?

**Comment by erasma** [comment]
I ran it using V12.22.9

**Comment by PuKoren** [comment]
Its too old and some code I am using won't work with it, do you have any way to run it with a more recent version ? I think node 14 might work

**Comment by erasma** [comment]
Thank you it's working installed version 20 now - so  ubuntu 20 comes with Version 12

**Comment by PuKoren** [comment]
Got it! Thanks
