### ISSUE TITLE
 const workshopid = root.querySelector(".stats-table a")?.innerHTML;

### ISSUE THREAD

**Issue by pmut** [PuKoren/rust-skins-config#2]
Hi,

when I run the index.js I get the following error.

`        const workshopid = root.querySelector(".stats-table a")?.innerHTML;
                                                                ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
`

Any Hint what the issue could be?

greetings

**Comment by pmut** [comment]
ok, found the closed issue. sorry :-)
